#! Custom cluster settings: drop this file to
#! .tkg/providers/infrastructure-vsphere/ytt.
#!
#! This file overrides YAML definitions from
#! .tkg/providers/infrastructure-vsphere/vX.Y.Z/ytt/base-template.yaml.
#! ---------------------------------------------------------------------

#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#! Let's override settings for cluster foo: worker nodes have more CPU/memory/disk.
#! We use the worker template name ("foo-worker") to match the nodes to patch.
#@overlay/match by=overlay.subset({"kind": "VSphereMachineTemplate", "metadata": { "name": "foo-worker" }})
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: VSphereMachineTemplate
spec:
  template:
    spec:
      diskGiB: 80
      memoryMiB: 8192
      numCPUs: 4
